@startuml

title __UTIL's Class Diagram__\n

  namespace Util {
    class Util.ChatMsg {
        {static} + chatMsgList : List<ChatMsg>
        - chatObj : String
        - content : String
        - iconID : int
        - isGroup : int
        - myInfo : boolean
        - username : String
        + getChatObj()
        + getContent()
        + getIconID()
        + getIsGroup()
        + getUsername()
        + isMyInfo()
        + setChatObj()
        + setContent()
        + setIconID()
        + setIsGroup()
        + setMyInfo()
        + setUsername()
    }
  }
  

  namespace Util {
    class Util.ImageManager {
        {static} + imageID : int[]
        {static} + imagesAvatar : int[]
        {static} + imagesBackground : int[]
    }
  }
  

  namespace Util {
    class Util.ImageMsg {
        - imageID : int
        + getImageID()
        + setImageID()
    }
  }
  

  namespace Util {
    class Util.LoginMsg {
        - password : String
        - username : String
        + LoginMsg()
        + LoginMsg()
        + getPassword()
        + getUsername()
        + setPassword()
        + setUsername()
    }
  }
  

  namespace Util {
    class Util.MomentMsg {
        {static} + momentMsgList : List<MomentMsg>
        - good : int
        - good_num : int
        - iconID : int
        - moment : String
        - time : String
        - userId : String
        + getGood()
        + getGoodNum()
        + getIconID()
        + getMoment()
        + getTime()
        + getUserId()
        + setGood()
        + setGoodNum()
        + setIconID()
        + setMoment()
        + setTime()
        + setUserId()
    }
  }
  

  namespace Util {
    class Util.RegisterMsg {
        - userName : String
        - userPwd : String
        + RegisterMsg()
        + getUserName()
        + getUserPwd()
    }
  }
  

  namespace Util {
    class Util.UserItemMsg {
        {static} + userItemMsgList : List<UserItemMsg>
        - avatarPath : String
        - createrId : String
        - groupId : String
        - groupName : String
        - itemType : int
        - sign : String
        - userId : String
        - userName : String
        + getAvatarPath()
        + getCreaterId()
        + getGroupId()
        + getGroupName()
        + getItemType()
        + getSign()
        + getUserId()
        + getUserName()
        + setAvatarPath()
        + setCreaterId()
        + setGroupId()
        + setGroupName()
        + setItemType()
        + setSign()
        + setUserId()
        + setUserName()
    }
  }
  



right footer


PlantUML diagram generated by SketchIt! (https://bitbucket.org/pmesmeur/sketch.it)
For more information about this tool, please contact philippe.mesmeur@gmail.com
endfooter

@enduml
